title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     Good Eats
  repo:     Savory

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: TACOS- WHY DO WE LOVE 
- title: # the title of the step, shown to the learner in the course progress page
  description: # a description of the step, shown to the learner in the course progress page
  event: issue_commented.created
  actions: # a list of the actions that will occur when the step is triggered by an event
- type: gate
  left: '%payload.pull_request.title%'
  operator: ===
  right: Add name to README
# Step 2: CHOOSE THE RIGHT PROTEIN
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # SO SO YUMMY
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: CHOOSE THE RIGHT SEASONING
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: HEAT WITH CARE
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: ENJOY THEM
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_commented.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

